### ISSUE TITLE
Election interference

### ISSUE THREAD

**Issue by guerrilla** [dessalines/essays#10]
I was going through the sources in this article: https://www.theguardian.com/commentisfree/2017/jan/05/americans-spot-election-meddling-doing-years-vladimir-putin-donald-trump

and I found Dov Levin's work:

http://www.dovhlevin.com/dissertation-and-other-research

He claims the US and the USSR/Russia interfered in 117 elections between '46 and '00. Unfortunately, it's behind a paywall and I can't access it. 

Any idea how we can get ahold of his PhD thesis? It and the journal articles are peer-reviewed. This should be gold.

**Comment by dessalines** [comment]
Not sure, I fkn hate paywalls.

**Comment by guerrilla** [comment]
I've asked a historian friend if he still has his academic credentials. I'll let you know...

**Comment by dessalines** [comment]
I'll reopen if this comes up.

**Comment by citizenkepler** [comment]
Not sure if this matters anymore but his website now has a dataset request form. This might be a way to get the data without the paywall

http://www.dovhlevin.com/datasets
