### ISSUE TITLE
Web Archive all links ? 

### ISSUE THREAD

**Issue by motorto** [dessalines/essays#106]
hey awesome lists you got here , but maybe web-archive all sites that are sources, a lot of the links I clicked are 404 or twitters deleted by the person already (don't know if web archive here would help )

Changing all the link is a lot of work , but maybe from now on only accept links in that format ?

**Comment by dessalines** [comment]
Good idea, I'll remind myself to do this from now on.

It'd also be handy if anyone knew of any program that can parse a file for URLs and add them to archive.org , and possibly replace them in that file.

**Comment by motorto** [comment]
Probably creating an issue wasn't the best way to get in contact with
you.

If its okay I will close this issue!
