### ISSUE TITLE
What's wrong in Indonesia

### ISSUE THREAD

**Issue by syakirahh3** [dessalines/essays#107]
https://megapolitan.kompas.com/read/2021/05/19/20300071/fakta-terkini-anak-anggota-dprd-bekasi-yang-perkosa-dan-jual-remaja-jadi?page

**Comment by dessalines** [comment]
Could you write up a point for that? I can't read it.

**Comment by syakirahh3** [comment]
actually i am not sure, but the new tells about The Son of a Bekasi DPRD Member Who Rape and Sells a Teenager, Becomes a Suspect, Has a Fugitive Status
