### ISSUE TITLE
Mexican Reparations

### ISSUE THREAD

**Issue by ChildishGiant** [dessalines/essays#109]
During the Great Depression, in the early 1930s, the United States deported between 500,000 and 2 million people of Mexican descent (including the illegal expulsion of up to 1.2 million U.S. citizens)

https://web.archive.org/web/20160822070322/http://digitalcommons.pace.edu/cgi/viewcontent.cgi?article=1147&context=plr

https://en.wikipedia.org/wiki/Mexican_Repatriation

**Comment by dessalines** [comment]
Thanks, I'll add these sources, esp under the operation wetback point.
