### ISSUE TITLE
Add evaluation of SimpleX?

### ISSUE THREAD

**Issue by sshine** [dessalines/essays#129]
Do you accept updates to your essay, or would you say that it's locked in time because the world is ever changing?

> SimpleX - the first chat platform that is 100% private by design

It gets a 5/5 rating in the essay's metrics, and it seems to be an ideological project.

https://github.com/simplex-chat/simplex-chat

The main caveat that I've experienced is that they don't make it very obvious how to self-host the server component.

So perhaps it is in category with Briar for being difficult to use, and very difficult to self-host.

**Comment by dessalines** [comment]
I guess it seems okay, but they must be at least somewhat user friendly, these are for general adoption.
