### ISSUE TITLE
Operation Sea-Spray

### ISSUE THREAD

**Issue by CommieSquid** [dessalines/essays#13]
I think [Operation Sea-Spray](https://en.wikipedia.org/wiki/Operation_Sea-Spray) belongs on the list. While it didn't cause serious long-term damage, it was a significant breach of medical ethics.

Draft for bullet point:
> In 1950, the US Navy sprayed bacteria over the San Fransisco Bay Area during [Operation Sea-Spray](https://en.wikipedia.org/wiki/Operation_Sea-Spray), one of the largest human experiments in history. The residents of the area were not informed, making the event a serious violation of the [Nuremberg Code](https://en.wikipedia.org/wiki/Nuremberg_Code) on medical ethics. In the following month, 11 residents checked in at a local hospital with a rare urinary tract infection, and the area saw a spike in pneumonia cases. This was one of numerous open-air tests of biological agents conducted by the US Armed Forces during the Cold War.

**Comment by dessalines** [comment]
Thanks! i'll add this shortly.
