### ISSUE TITLE
Essay suggestion

### ISSUE THREAD

**Issue by TPS** [dessalines/essays#138]
Could there be an essay or even stub on how the large socialist implementations of past & present could've/should be improved?  I've always wanted to see such, as the greatest intentions have always seemed to fall short of the best ideals.

**Comment by dessalines** [comment]
I have one essay on a cyber communist syste, linked in the readme, and there's a few sections in the faq that go over socialist difficulties and experimentation. But it's too large a subject for me to devote time to an essay about at the moment.
