### ISSUE TITLE
Correction needed in why_not_signal.md - contains bad information about Radio Free Asia

### ISSUE THREAD

**Issue by bplein** [dessalines/essays#143]
Re: why_not_signal.md
https://github.com/dessalines/essays/blob/a6bd0893a5e8f3b511af56a888f5dd88e698b1ed/why_not_signal.md?plain=1#L71C1-L93C4

The whole idea that the CIA funded Signal, directly or indirectly, hinges on the fact that in the 1950s, the CIA fund and operate an organization called Radio Free Asia (RFA), and your claim that the 1950s RFA and the current RFA are one and the same organization.

That original RFA is not, in fact, the same organization as the current extant Radio Free Asia.

[WIkipedia Radio Free Asia disambiguation](https://en.wikipedia.org/wiki/Radio_Free_Asia_(disambiguation))

The true lineage of the old CIA run Radio Free Asia, as part of Committee for Free Asia, is that it stopped transmitting in the 1950s and the Committee changed its name to The Asia Foundation, which severed its ties to the CIA in the 1960s. See this [archived NY Times article on propaganda](https://web.archive.org/web/20190704055350/https://www.nytimes.com/1977/12/26/archives/worldwide-propaganda-network-built-by-the-cia-a-worldwide-network.html)

The current RFA was created in the 1990s, and if it has links to the CIA, they've been well hidden for over 25 years.

In fact, you use the same NY Times article, hinting that Radio Free Asia was simply a re-branding effort, although it's the same organization from the 1950's, but the article has nothing to support your claim. 

According to [the Wikipedia article about the modern RFA](https://en.wikipedia.org/wiki/Radio_Free_Asia), the current RFA was initially formed, new, as a differently named organization, and only under pressure from one of the most conservative and unabashedly racist Republican senators of modern times, forced the renaming to the old Radio Free Asia moniker. 

"Extraordinary claims require extraordinary evidence", as Dr. Carl Sagan once said, and I believe this section requires more citations, if you can find them.

**Comment by dessalines** [comment]
From the very first line of the wiki article you linked about the modernized RFA:

> Radio Free Asia (RFA) is a [United States government](https://en.m.wikipedia.org/wiki/United_States_government)-funded private [non-profit](https://en.m.wikipedia.org/wiki/Nonprofit_organization) [news service](https://en.m.wikipedia.org/wiki/News_agency) that [broadcasts](https://en.m.wikipedia.org/wiki/News_broadcasting) radio programs and publishes online news, information, and commentary for its audiences in [Asia](https://en.m.wikipedia.org/wiki/Asia).

**Comment by bplein** [comment]
So, while not denying that your linkage and prose is not accurate, you simply redirect to a different claim or fact, and I am guessing you’ll use that as justification to keep your specious argument as canon. The US government also funds PBS, but that does not make PBS a CIA arm. 

Oh well. I might agree with the direction your politics but I can’t support disinformation in the cause of said goals. Buh bye.
