### ISSUE TITLE
Dead reddit links

### ISSUE THREAD

**Issue by discomrade** [dessalines/essays#145]
I've only checked the [Is China State Capitalist?](https://dessalines.github.io/essays/socialism_faq.html#is-china-state-capitalist) section so far. There are two dead links:
- [How is SWCC not revisionist? How is it any different from Gorbachev’s market reforms?](https://www.reddit.com/r/GenZhou/comments/quohro/market_reforms_vs_revisionism/hkrptbm/)
- [A China misinformation Megathread.](https://old.reddit.com/r/communism/comments/c2b7ma/china_megathread_everything_a_leftist_must_know/)

I can't currently check if they are archived by Wayback Machine or archive.today, but this could be a good option for reddit links due to their volatility.

**Comment by dessalines** [comment]
Thanks, I got these ones. It'd be hugely helpful if you could fix these tho, I'm very busy.
