### ISSUE TITLE
Add las vegas shooting to hate crimes

### ISSUE THREAD

**Issue by dessalines** [dessalines/essays#38]

**Comment by OKNoah** [comment]
Was the Las Vegas shooting a hate crime? The mass shooting?

**Comment by dessalines** [comment]
I'm putting mass shootings in there too, since the US has the highest proportion of mass shootings per capita in the world.

**Comment by OKNoah** [comment]
@dessalines Don't forget Tulsa race riots and Elaine massacre. Biggest mass shootings in US history (often ignored in mainstream media).

> Tulsa race riots: A white mob attacked black residents in Tulsa, Okla., in 1921 and burned down the Greenwood neighborhood, which was then the wealthiest black business district in the United States. Modern estimates place the death toll at 50 to 300 people, many of them shot.

> Elaine massacre: Black men in Elaine, a small town in eastern Arkansas, met in the fall of 1919 to discuss how to collect more money for their cotton crops. During the meeting, a white man who was deputized was shot. In the riot that followed, as many as 200 black people were shot and killed.

From: http://www.latimes.com/nation/la-na-mass-shooting-20160614-snap-story.html

**Comment by dessalines** [comment]
Thanks! I have the tulsa race riots in [this section](https://github.com/dessalines/essays/blob/master/us_atrocities.md#black-people) of the US atrocities page, cause the local police and national guard assisted, but I'll add it to this list too. I'll add the other one to both.
