### ISSUE TITLE
Bikini Atoll

### ISSUE THREAD

**Issue by guerrilla** [dessalines/essays#4]
https://en.wikipedia.org/wiki/Nuclear_testing_at_Bikini_Atoll

John Pilger's documentary called "The Coming War on China" documents this extensively (it's 1/3 of the film.)

**Comment by dessalines** [comment]
If you'd like, since you probably know a good deal about this, could you write up a bullet point for it here? You could also click that little pencil edit button on the main page and click submit a pull request. 

If not, lemme know and I'll do some research and write up a point for it.

**Comment by guerrilla** [comment]
I'm gonna put it here because I'm too lazy to figure out the markdown...

- Between 1946 and 1958, the United States tested 23 nuclear devices at Bikini Atoll. Some residents were moved to Rongerik Atoll and kili Island. Both locations (as well as Bikini Atoll) proved unsuitable to sustaining life, resulting in starvation and requiring the residents to receive ongoing aid. Originally, the Navy left them there with a few weeks of food which proved insufficient. Significant fallout caused widespread radiological contamination in the area. Evacuation only began 2 and 3 days later. Virtually all of the inhabitants showed acute symptoms of radiation syndrome. A handful were brought to the US for medical research and later returned. When the majority returned 3 years later, radion levels were still unacceptable. Similar incidents occurred elsewhere in the Marshall Islands during this time period. Because of the destruction of natural wealth, Kwajalein Atoll's military instillation and dislocation, the majority of natives now live in extreme poverty, making less than 1$ a day. those that have jobs, mostly work at the US military installation and resorts.

1. https://en.wikipedia.org/wiki/Nuclear_testing_at_Bikini_Atoll

2. http://hellomarshallislands.weebly.com/poverty.html

**Comment by guerrilla** [comment]
"resort" is not the right word. It's more like a gated community for government, diplomats, land-owners and US military personel.... I don't know how to phrase it, the blurb is already relatively long
