### ISSUE TITLE
feedback on socialism_faq

### ISSUE THREAD

**Issue by brucedaniel** [dessalines/essays#53]
Thanks for the info, I have a lot to learn!

IMO, that FP piece does not provide enough to get to the rather eye-catching claim re the reason Japan surrendered. I think you need a source with more than circumstantial evidence for that claim. Strongest argument in there is "why did it take 3 days to convene the surrender council if it was the Hiroshima bomb that did it". A puzzling question one does not know the answer to is not positive evidence.

**Comment by dessalines** [comment]
There are many other arguments in there besides timing (which was actually pretty important if you read this section): 

> Second, the preliminary report prepared by the Army team that investigated the Hiroshima bombing, the one that gave details about what had happened there, was not delivered until Aug. 10. It didn’t reach Tokyo, in other words, until after the decision to surrender had already been taken. Although their verbal report was delivered (to the military) on Aug. 8, the details of the bombing were not available until two days later. The decision to surrender was therefore not based on a deep appreciation of the horror at Hiroshima.

Also scale, namely that hiroshima wasn't any more significant than any of the other hundreds of cities that were bombed:

> In the three weeks prior to Hiroshima, 26 cities were attacked by the U.S. Army Air Force. Of these, eight — or almost a third — were as completely or more completely destroyed than Hiroshima (in terms of the percentage of the city destroyed). The fact that Japan had 68 cities destroyed in the summer of 1945 poses a serious challenge for people who want to make the bombing of Hiroshima the cause of Japan’s surrender. The question is: If they surrendered because a city was destroyed, why didn’t they surrender when those other 66 cities were destroyed?

The most damning evidence though, is that the journals of the japanese generals highlighted the soviet entrace into the war as the most important factor:

> The impact of the Soviet declaration of war and invasion of Manchuria and Sakhalin Island was quite different, however. Once the Soviet Union had declared war, Stalin could no longer act as a mediator — he was now a belligerent. So the diplomatic option was wiped out by the Soviet move. The effect on the military situation was equally dramatic. Most of Japan’s best troops had been shifted to the southern part of the home islands. Japan’s military had correctly guessed that the likely first target of an American invasion would be the southernmost island of Kyushu. The once proud Kwangtung army in Manchuria, for example, was a shell of its former self because its best units had been shifted away to defend Japan itself. When the Russians invaded Manchuria, they sliced through what had once been an elite army and many Russian units only stopped when they ran out of gas. The Soviet 16th Army — 100,000 strong — launched an invasion of the southern half of Sakhalin Island. Their orders were to mop up Japanese resistance there, and then — within 10 to 14 days — be prepared to invade Hokkaido, the northernmost of Japan’s home islands. The Japanese force tasked with defending Hokkaido, the 5th Area Army, was under strength at two divisions and two brigades, and was in fortified positions on the east side of the island. The Soviet plan of attack called for an invasion of Hokkaido from the west.

> It didn’t take a military genius to see that, while it might be possible to fight a decisive battle against one great power invading from one direction, it would not be possible to fight off two great powers attacking from two different directions. The Soviet invasion invalidated the military’s decisive battle strategy, just as it invalidated the diplomatic strategy. At a single stroke, all of Japan’s options evaporated. The Soviet invasion was strategically decisive — it foreclosed both of Japan’s options — while the bombing of Hiroshima (which foreclosed neither) was not.

> The Soviet declaration of war also changed the calculation of how much time was left for maneuver. Japanese intelligence was predicting that U.S. forces might not invade for months. Soviet forces, on the other hand, could be in Japan proper in as little as 10 days. The Soviet invasion made a decision on ending the war extremely time sensitive.

> And Japan’s leaders had reached this conclusion some months earlier. In a meeting of the Supreme Council in June 1945, they said that Soviet entry into the war “would determine the fate of the Empire.” Army Deputy Chief of Staff Kawabe said, in that same meeting, “The absolute maintenance of peace in our relations with the Soviet Union is imperative for the continuation of the war.”
