### ISSUE TITLE
Need an elaboration on why/how.  

### ISSUE THREAD

**Issue by manykwh** [dessalines/essays#54]
The end of the first paragraph under the section "_History, and Human Nature_" under the essay "_Crash Course Socialism_" is so powerful that it got me to stop reading and finally take an action (opening this ticket).  I didn't even finish reading the page yet.  FYI/Disclaimer I am male sex/gender.  

> **Private property** (and male-dominated societies) came into existence with the growth of large-scale agriculture and animal domestication (A historically male-dominated activity).  These tended **to be passed on to male** descendants (which in turn **required** strict female sexual control, isolation, and increasing objectification), aggregating into fewer and fewer land-owners, and creating class antagonisms between an owning, and a working class.

If the author meant to say "_resulted in_" and not "_required_", then that's it.  But otherwise, I would like the author to elaborate on the following things please:

> ...(which in turn required strict female sexual control, 

Why was/is strict female **sexual** control required for private property to be granted to males?  Did you mean to say "_resulted in_", and not "_required_"?  I just don't see how sex has anything to do with it.  

> isolation, 

If males are already strictly controlling females sexually, why is additional isolation (from whom, anyway?) required?  What kind of additional isolation are we talking about here?  I get it, the bigger the farm the harder it is to travel, particularly before the proliferation of females operating automobiles.  Keep in mind, in modern times, automobile operation skill is not necessarily a result of their sex or gender, so this could extend to before automobiles.  Why then, did females comply with the isolation which was required for private property to be traded to male descendants?  Trapping a female on your vast endless farm for their entire life to control them sexually is basically rape.  

> and increasing objectification), 

Right, objects don't inherit ownership status, _people_ do.  But how did women end up objectified by men if this was _required_ to happen?  Why did women put up with being objectified?  Is there something I missed when I was a kid?  

>aggregating into fewer and fewer land-owners, 

So each generation is a game of monopoly for its members.

> and creating class antagonisms between an owning, and a working class.)

And losers become workers and their descendants have a chance, albeit at a higher difficulty level, of winning the monopoly game.  But what does strict female sexual control, isolation and increasing objectification have anything to do with the player's ability to win the game of monopoly?

**Comment by dessalines** [comment]
This isn't a help forum. I'd suggest asking this at https://reddit.com/r/communism101 .
