### ISSUE TITLE
Add more anti-indigenous genocidal acts

### ISSUE THREAD

**Issue by catzs** [dessalines/essays#58]
https://en.wikipedia.org/wiki/Pequot_War

https://en.wikipedia.org/wiki/Ishi - dehumnization / ontological violence

Boarding schools: http://www.citylights.com/book/?GCOI=87286100529180

https://en.wikipedia.org/wiki/American_Indian_boarding_schools

https://deathpenaltyinfo.org/native-americans-and-death-penalty

https://en.wikipedia.org/wiki/Cypress_Hills_Massacre

https://en.wikipedia.org/wiki/Apache_Wars

Remains disposession: https://web.archive.org/web/20061026000018/http://news.independent.co.uk/world/americas/article622744.ece

https://web.archive.org/web/20090228230912/http://www.abqjournal.com/abqnews/index.php?option=com_content&view=article&id=10846%3A635am-geronimo-died-100-years-ago-today&catid=1%3Alatest&Itemid=39

https://www.kqed.org/news/11680078/native-american-tribes-clash-with-uc-over-bones-of-their-ancestors

Aleut oppression - https://education.blogs.archives.gov/2016/03/29/aleut-women-petition/

https://www.nps.gov/aleu/learn/historyculture/unangan-internment.htm

Nuclear genocide - https://www.culturalsurvival.org/publications/cultural-survival-quarterly/nuclear-war-uranium-mining-and-nuclear-tests-indigenous

To counteract disease reductionism - https://uapress.arizona.edu/book/beyond-germs

Theft - https://supportblackmesa.org/2014/10/sheep-emergency-fund-for-black-mesa-families-targeted-by-unjust-livestock-impoundments/

https://supportblackmesa.org/2014/10/requesting-immediate-support-for-hopi-partition-land-hpl-residents-whose-livestock-are-being-impounded-by-hopi-rangers-and-federal-agents/

Black mesa issue - https://law.lclark.edu/live/files/5648

Police murder - https://www.lakotalaw.org/news/2017-11-21/native-lives-matter-the-overlooked-police-brutality-against-native-americans

https://thenib.com/native-lives-matter

https://publicintegrity.org/federal-politics/murdered-and-missing-native-american-women-challenge-police-and-courts/https://journals.sagepub.com/doi/abs/10.1177/2153368717734614

Land / site desecration/theft - https://bsnorrell.blogspot.com/search?updated-max=2018-11-17T21:56:00-07:00&max-results=6&start=12&by-date=false

https://survivalsolidarity.wordpress.com/2011/11/24/oodham-sacred-site-of-quitovac-once-again-under-threat-from-us-gold-mining-company-silver-scott-mines/

Ojibwe oppression - https://tribalcollegejournal.org/nanaboozhoo-wiindigo-ojibwe-history-colonization-present/

Occupation/militarization of Nicoleno land for imperialist purposes - https://en.wikipedia.org/wiki/San_Nicolas_Island

Foster care system - https://www.npr.org/series/141763531/native-foster-care-lost-children-shattered-families

https://www.americanbar.org/content/dam/aba/publishing/insights_law_society/ChildProtectionHistory.authcheckdam.pdf

Refusal to recognize indigenous land - https://en.wikipedia.org/wiki/Indian_Appropriations_Act#1871_Act

Menominee history - https://www.lafollette.wisc.edu/images/publications/otherpublications/menominee.pdf

Violence in the justice system - https://deathpenaltyinfo.org/native-americans-and-death-penalty

**Comment by dessalines** [comment]
Thanks, I'll get to these within a week or so, unless you wanna write the lines instead.

**Comment by Anarcho-Bolshevik** [comment]
Big Oil Linked to Human Trafficking of Indigenous Women and Girls: https://www.projectcensored.org/?p=20479

**Comment by dessalines** [comment]
This is too much for me to add. Please create these points as paragraphs.
