### ISSUE TITLE
Re: Arch Linux

### ISSUE THREAD

**Issue by temtemy** [dessalines/essays#61]
I wonder why you recommend Arch Linux. Yes, it uses the upstream's source code unlike Debian, but you would have to update your system every day. Unless you're a software developer, a software tester, or insane, I would not recommend Arch. Bugs can be a nightmare. If I were you, I would recommend Debian stable, Trisquel, which is a FSF-endorsed Ubuntu variant (since Ubuntu has spyware and recommends nonfree software), or PureOS, a FSF-endorsed Debian variant focusing on user-friendly security and privacy.

**Comment by dessalines** [comment]
I think you're just referring to my personal favorite apps file? Those are just recommends, nothing too special. If it were security we should pry be recommending tails or qubes over anything.
