### ISSUE TITLE
Reform or Revolution low audio level.

### ISSUE THREAD

**Issue by boomboompsh** [dessalines/essays#68]
The version of your recording of Reform or Revolution available on marxists.org has a terrible volume issue on chapter 10. I have verified that your torrent link on GitHub is the same. The audio is barely audible, and when using an analog audio cable to listen in the car, the signal to noise ratio is unacceptable. I got it to be listenable by setting all equalizer sliders to maximum, but it was still much worse than the other chapters. Measuring it in audacity, the volume on chapter 10 is 32.42 dB below chapter 9. I sent a message through reddit, but decided it would be better to put this on the bug tracker.

**Comment by dessalines** [comment]
I might not be able to fix it, considering the torrents heavily seeded, but once I get back in a fem days ill see if its completely unlistenable. Sry about that BTW.

**Comment by dessalines** [comment]
I agree it is pretty low, I might not be able to fix it now.
