### ISSUE TITLE
Add Raid on Yakla to us_atrocities

### ISSUE THREAD

**Issue by Nutomic** [dessalines/essays#69]
Seems like it would fit in. 25 civilians, including children, were murdered by US soldiers during a botched raid in Yemen.

https://en.wikipedia.org/wiki/Raid_on_Yakla

**Comment by dessalines** [comment]
Thx, I'll add this soon.

**Comment by dessalines** [comment]
Oh nm, I noticed this is already here in this line:

In 2010, President Obama directed the CIA to assassinate an American citizen in Yemen, Anwar al-Awlaki, despite the fact that he had never been charged with any crime, killing him with a September, 2011 drone strike. Two weeks later, a separate CIA drone strike in Yemen killed his 16-year-old American-born son, Abdulrahman, along with the boy’s 17-year-old cousin and several other innocent Yemenis. In January 2017, Trump ordered a SEAL strike, and reports from Yemen quickly surfaced that 30 people were killed, including 10 women and children. Among the dead: the 8-year-old daughter of Anwar Awlaki, sister of the 16 year old killed by Obama. 1

**Comment by Nutomic** [comment]
Oh sorry, I Ctrl-F'd throught the list but ignored that entry because it had the year 2010.
