### ISSUE TITLE
Speculative: Mozambique

### ISSUE THREAD

**Issue by guerrilla** [dessalines/essays#7]
The pattern of Mozambique is identical to Angola. RENAMO (opposition) was funded by Rhodesia; it's likely Kissinger and/or CIA was involved. Rhodesian CIO absolutely was.

https://en.wikipedia.org/wiki/RENAMO
https://en.wikipedia.org/wiki/Mozambican_Civil_War

**Comment by dessalines** [comment]
I looked through the articles but unfortunately couldn't find anything. It looks like the loyalists definitely were aided by Rhodesia and white south africa, which were directly funded by the CIA, but this one appears to be at least once removed. I couldn't find any references to CIA or direct US involvement on either of those pages unfortunately. I'll reopen if we can find some better sources.

**Comment by Anarcho-Bolshevik** [comment]
https://www.projectcensored.org/?p=13593
