### ISSUE TITLE
STD experiments in Guatemala 

### ISSUE THREAD

**Issue by haysquirt** [dessalines/essays#74]
Similar to the Tuskegee experiments:

First, Do No Harm: The US Sexually Transmitted Disease Experiments in Guatemala
Michael A. Rodriguez, MD, MPH corresponding author and Robert García, JD

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3828982/

**Comment by haysquirt** [comment]
I pinned the atrocities essay to my Twitter @haysquirt.  

This Pubmed article was sent to me be another Twitter user.

**Comment by dessalines** [comment]
Could you add a line for this, I'm really busy at the moment.
