### ISSUE TITLE
In the 1950s, they detained & deported a scientist for being Chinese

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [dessalines/essays#76]
https://www.pri.org/node/157066

**Comment by dessalines** [comment]
I'll add this within a few days.

**Comment by Anarcho-Bolshevik** [comment]
Here’s the sequel that nobody asked for! https://www.liberationnews.org/?p=81917

https://www.scmp.com/magazines/post-magazine/long-reads/article/3016267/chinese-scientists-guilty-researching-while
