### ISSUE TITLE
What’s wrong with John F. Kennedy?

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [dessalines/essays#78]
I would like to recommend that we include a section on JFK. He is a typical hero for neoliberals, and is perhaps sometimes cited as an example of anticommunism at its finest. While it’s probably accurate to say that his régime was somewhat moderate in comparison to those that succeeded it (which was probably what motivated [internal forces](http://www.rationalrevolution.net/war/us_military_drafted_plans_for_do.htm) to kill him), he was still a war criminal worthy of the White House’s legacy. Here are some facts that I know about him:

Perhaps the most obvious is that JFK, like his henchmen, was a bellicist who green‐lit the Bay of Pigs invasion. I have read that his régime also enjoyed making plans to murder the heads of state in rival countries, and they were the ones who launched the campaign to murder Fidel Castro after the invasion against the Republic of Cuba failed. (These failures contributed to the so‐called Cuban Missile Crisis.) On [September 2, 1963](https://jakemabe.blogspot.com/2011/01/vintage-cbs-interview-debunks.html), JFK told Walter Cronkite that ‘_These people who say we ought to withdraw from Vietnam are wholly wrong, because if we withdrew from Vietnam, the communists would control Vietnam, pretty soon […] all of Southeast Asia would be under control of the communists and […] then India, Burma would be the next target._’ This formed the basis for the interventionist propaganda of later years; it was nothing new. [JFK was in favour of the terroristic arms chase](https://web.archive.org/web/20130329100239/http://faculty.virginia.edu/nuclear/vault/readings/Bulletin%20-%20Camelot%27s%20Nuclear%20Conscience.pdf); the [‘missile gap’](https://www.theatlantic.com/magazine/archive/2013/08/what-missile-gap/309484) [that helped get him elected was a lie all along, and he was well aware of it.](https://100days.blogs.nytimes.com/2009/02/10/missile-gaps-and-other-broken-promises) And while not exactly evil, it may be interesting to note that [his régime authorized the forcible replacement of their own neocolonial one in Vietnam](https://nsarchive2.gwu.edu//NSAEBB/NSAEBB101/vn02.pdf) with something more trustworthy for them, [but they’re why it existed in the first place!](http://www.rationalrevolution.net/war/american_involvement_in_vietnam.htm)

[JFK was also supportive of Nixon.](https://gregmitchellwriter.blogspot.com/2014/10/when-jfk-backed-nixon-against-famous.html) Despite JFK being somewhat more moderate, he voted in support of Nixon’s cosponsored security legislation, voted with Nixon to continue the House Un‐American Activities Committee, and personally backed Nixon in his 1950 Congressional bid against another candidate. Nixon said nothing about the JFK régime’s budget overruns and escalations in Vietnam. [They even held a similar attitude towards the civil rights movement](https://www.pbs.org/wgbh/americanexperience/features/kennedys-and-civil-rights) and [liked wiretapping others.](https://books.google.com/books?id=je5zAgAAQBAJ&pg=PT26)

JFK was also a casual misogynist who not only cheated on his spouse repeatedly, but didn’t even care about satisfying the people that he slept with. I have read that he slept with every woman who worked for the White House, and many other women who worked outside of it, [including sex workers, many of whom he snapped photos (that his agents later framed)](https://www.nydailynews.com/archives/news/book-camelot-sex-playpen-sez-jack-insatiable-article-1.777486); he [told Prime Minister Harold Macmillan that he couldn’t go three days without having sex, otherwise he would experience ‘severe headaches’.](https://books.google.com/books?id=FNTFJ1aqXcwC&pg=PA362) His agents used Mickelson’s Fine Picture Framing and Gallery to hold his pornographic photos: [the same gallery that Jacqueline Kennedy was using for the White House’s restortation](https://www.jfklibrary.org/JFK/JFK-in-History/The-White-House-Restoration.aspx); [Mickelson was uncomfortable.](https://books.google.com/books?id=WRjmlhjE2ggC&focus=searchwithinvolume&q=mickelson) [JFK’s sexual addiction only got worse as his career continued](https://www.theatlantic.com/past/docs/unbound/bookauth/nov22.htm), so much so that later [Lyndon Johnson used him in a comparison.](https://books.google.com/books?id=laNFP5LtKUIC&pg=PA540) In addition, [JFK himself was very probably against abortion](https://www.lifenews.com/?p=60682) (though this is not absolutely certain given that Americans rarely discussed abortion before the 1970s).

Contrary to popular belief, [the space race had little public support](https://www.gallup.com/poll/3712/landing-man-moon-publics-view.aspx), and interestingly, [only 53% of U.S. citizens believe that the moon landing was worth the cost.](https://www.smithsonianmag.com/science-nature/ten-enduring-myths-about-the-us-space-program-1969206)

And perhaps least importantly, [he was a lifetime member of the NRA](https://books.google.com/books?id=QXeGX67ezSYC&pg=PA5), and [the NRA liked him so much that they were in favour of gun restrictions after somebody shot him.](https://www.newyorker.com/magazine/2012/04/23/battleground-america)

Addendum: the [JFK régime later noticed how provocative their actions were against the Republic of Cuba.](https://books.google.com/books?id=Eaws3G98Ji0C&pg=PA48) Their [illegal obstruction against them only escalated the so‐called Cuban Missile Crisis](https://www.theatlantic.com/magazine/archive/2013/01/the-real-cuban-missile-crisis/309190), and at one point [they seriously considered reinvading the Republic of Cuba.](https://muse.jhu.edu/article/446359/pdf)

Readdendum: [more examples here.](https://www.buzzfeednews.com/article/irastoll/21-ways-jfk-was-actually-a-conservative-fjkq)

**Comment by dessalines** [comment]
Very good point, I'll add these points sometime within the next week or so to the FAQ.

**Comment by Anarcho-Bolshevik** [comment]
[Young Kennedy also claimed that ‘Fascism seems to treat [Italians] well.’](https://books.google.com/books?id=mfYxUPyKPs0C&pg=PT74) He did complain about the arrogance that many people in Germany exhibited and he made fun of their salute, but nothing substantial. [He was quite tolerant of Cold War Fascism](https://archive.org/stream/TheHoaxers#page/n616/mode/1up) and [Axis collaborators.](https://books.google.com/books?id=R3qdAwAAQBAJ&pg=PT235)
