### ISSUE TITLE
Internal Repressions Black People Addition

### ISSUE THREAD

**Issue by Ravenclaw968** [dessalines/essays#81]
Between the 1950s and the 1970s, predatory contracts called "home sale contracts" were given to 75% of the 60,100 homes purchased by black Chicaogans. These "home sale contracts" allowed the seller to hold the property until the buyer paid off the entire mortgage. This meant that no equity was accrued by the buyer and the owners could kick the buyers out if a single monthly payment was missed. Black contract buyers in Chicago payed an average of $71,000 more than they would have through a conventional non-predatory mortgage. In total, between $3.2 billion and $4 billion were [expropriated from Chicago's black community](https://chicago.suntimes.com/2019/5/30/18644165/chicago-redlining-racism-real-estate-contract-rent-mortgages-black-homeownership-racial-wealth-gap).

**Comment by dessalines** [comment]
Thx for this btw.

**Comment by Anarcho-Bolshevik** [comment]
Back in the early 1980s, an [all‐white jury in Philadelphia sentenced Black Panther Mumia Abu-Jamal to death](https://owd.tcnj.edu/~kpearson/Mumia/part5.htm) for [supposedly murdering a police officer.](https://owd.tcnj.edu/~kpearson/Mumia/parrt4.htm) Tellingly, [one of the judges referred to Abu‐Jamal with a racial slur.](http://www.mumia.de/doc/aktuell/20010903mde02en.html)

**Comment by Ravenclaw968** [comment]
Wall Street and other banks profit off of buying bonds from state and local governments who pay for the police’s legal fees when cases of police brutality are brought to court. Banks reaped tax-payer money of $1.03 billion in profit from the interest for five cities (Chicago, Cleveland, Lake County, Los Angeles, and Milwaukee) over a ten year period. (http://nathancummings.org/wp-content/uploads/PoliceBrutalityBonds-Jun2018-1.pdf)
