### ISSUE TITLE
Attempts to curtail Cuba from exporting medical services?

### ISSUE THREAD

**Issue by dlcmh** [dessalines/essays#85]
This counts as an atrocity in my book
- https://apnews.com/98cfdbf5c4a62a40eba648723e452f3e
- https://www.iol.co.za/news/politics/us-criticises-south-africas-use-of-cuban-doctors-in-fight-against-covid-19-47384258

**Comment by dessalines** [comment]
I'm really busy at the moment, could you write up a point for this?
