### ISSUE TITLE
What about Boris Yeltsin?

### ISSUE THREAD

**Issue by guerrilla** [dessalines/essays#9]
https://www.theguardian.com/commentisfree/2017/jan/05/americans-spot-election-meddling-doing-years-vladimir-putin-donald-trump

http://www.nytimes.com/1996/03/27/world/10.2-billion-loan-to-russia-approved.html

I wouldn't go so far as to claim that the US helped get him in during/after the August '91 coup d'etat but they obviously supported him, even giving him a 10.2$ billion loan in the run-up to the '96 election. Which in a way, is kind of worse, right, because at that point everyone knew he was ruining the country and totally unfit to even run a small business...

**Comment by dessalines** [comment]
Very true, I'll add this.
