### ISSUE TITLE
Regarding Garry Web and the CIA

### ISSUE THREAD

**Issue by Bruhtm** [dessalines/essays#93]
> In 1996, investigative journalist Gary Webb exposed a CIA-run business of selling cocaine produced  in Nicaragua, to help fund the anti-communist Contras in their fight against the Sandinistas in Nicaragua. These drugs were mostly sold to black communities in California, and helped spark the Crack epidemic. Several of the US dealers such as such as Ross and Oscar Danilo Blandon, were found to have CIA and DEA ties. Webb's reports were surpressed in the news media. In 1997, Webb stated: "If we had met five years ago, you wouldn't have found a more staunch defender of the newspaper industry than me ... And then I wrote some stories that made me realize how sadly misplaced my bliss had been. The reason I'd enjoyed such smooth sailing for so long hadn't been, as I'd assumed, because I was careful and diligent and good at my job ... The truth was that, in all those years, I hadn't written anything important enough to suppress." In 2004, Webb was found dead in his home, shot in the back of the head twice. His death was ruled a suicide.

Decades-old Fake News. CIA's own inspector general report, the several congressional committees, and DOJ's several investigations found that there was no evidence to substantiate the allegations of Gary Webb's ‘Dark Alliance’ series:

https://www.cia.gov/news-information/press-releases-statements/press-release-archive-1998/pr100898.html "Volume I of the report, which was issued on January 29, 1998, **found no evidence** that would substantiate The San Jose Mercury News allegations that the **CIA had any involvement** with Ricky Ross, Oscar Danilo Blandon, or Juan Norwin Meneses, or in cocaine trafficking in California to raise funds for the Contras."

https://www.cia.gov/news-information/press-releases-statements/press-release-archive-2000/house_pr05112000.html "In summarizing its findings, the Committee stated: "The allegations of the ‘Dark Alliance’ series warranted an investigation, and the Committee performed its role mindful of the thousands of American lives that have been lost to the scourge of crack cocaine. Based on its investigation, involving numerous interviews, reviews of extensive documentation, and a thorough and critical reading of other investigative reports, the Committee has concluded that **the evidence does not support the implications of the San Jose Mercury News—that the CIA was responsible for the crack epidemic in Los Angeles or anywhere else in the United States to further the cause of the Contra war in Central America.**"

**Comment by yearofglad** [comment]
Lmao no
